services:
  app:
    image: steve
    command: ["/app/ubot"]
    ports:
      # - "2833:8080"
    volumes:
      - ./data:/data
      - ./assets/dejavu:/usr/share/fonts/truetype/dejavu
    environment:
      - TZ=Asia/Kolkata
